### ISSUE TITLE
Up and Down methods for seeds like migrations

### ISSUE THREAD

**Issue by cve** [slampenny/SmartSeeder#10]
Hi,

first of all big thank you for that package, this is what I'm looking for, but I see that after runing rollback nothink was changed in my db, the data is the same as before. So maybe seed classes should have two methods up and down like migrations has, so the developer can write what will happen when data is pushing to and pulling from db?

When I run php artisan migrate:refresh --seed the second time then integrity constraint violations are thrown because the data still exists in db even if I run seed:rollback or seed:reset

Is there any solution for that problem?

**Comment by slampenny** [comment]
Sorry It took me so long to get back to you about this. I wanted to do an "up/down" but we'd have to get keys back from each call (so that we knew which records to delete on a "down" call) and then store them somewhere. With concatenated keys that can get complex, not to mention prohibitive in terms of space when you have multiple environments. In the end I thought it wasn't worth it to implement.
